# 🐼 PANDAS MASTERY - Learning
## From Absolute Basics to Real-World Applications

**Author:** Tuvya Algotar  
**Institution:** NMIMS Navi Mumbai | B.Tech AI & Data Science  
**Date:** April 2026  
**Goal:** Master Pandas for Data Science and Machine Learning

---
## 📚 What I'll Learn:

### Part A: FUNDAMENTALS (Cells 1-15)
- What is Pandas and why use it?
- Series vs DataFrame
- Creating data structures
- Basic operations
- Indexing and selection

### Part B: DATA MANIPULATION (Cells 16-30)
- Filtering and sorting
- Adding/removing columns
- Handling missing data
- String operations
- Datetime handling

### Part C: ADVANCED OPERATIONS (Cells 31-45)
- Groupby and aggregation
- Merging and joining
- Pivot tables
- Apply and map functions
- Data cleaning techniques

### Part D: REAL-WORLD APPLICATIONS (Cells 46-60)
1. Student Performance Analysis
2. E-commerce Sales Dashboard
3. COVID-19 Data Analysis
4. Movie Ratings Analysis
5. Stock Market Analysis

---

**Total cells:** 60+  
**Estimated time:** 4-6 hours for complete mastery  
**Prerequisite:** Basic Python (you already have this!)

In [2]:
import pandas as pd
import numpy as np

In [4]:
print("Pandas version: ",pd.__version__)
print("\nPandas is ready to use")

Pandas version:  2.3.3

Pandas is ready to use

In [7]:
# Creating a series

grades = pd.Series([85,45,93,23,80])
print("Series from list: ")
print(grades)
print("\nType : ",type(grades))

Series from list:
0    85
1    45
2    93
3    23
4    80
dtype: int64

Type :  <class 'pandas.core.series.Series'>

In [12]:
# Method 2 - Using custom index
grades_named = pd.Series(
    [85,90,78,82,99],
    index=['Math','Physics','Chemitry','Biology','CS']
)
print("Series with custom index: ")
print(grades_named)

# Accessing a name
print("\nMath grade: ",grades_named["Math"])
print("\nCS grade: ",grades_named["CS"])

Series with custom index:
Math        85
Physics     90
Chemitry    78
Biology     82
CS          99
dtype: int64

Math grade:  85

CS grade:  99

In [38]:
#Method 3 - FRom a dict

student_scores = {
    'Tuvya' : 85,
    'Rahul' : 34,
    'Priya' : 56,
    'Raj' : 82
}

scores_series = pd.Series(student_scores)
print("Series from dictionary:")
display(scores_series)

print("\nRahul score: ",scores_series['Rahul'])

Series from dictionary:

Tuvya    85
Rahul    34
Priya    56
Raj      82
dtype: int64

Rahul score:  34

In [29]:
# Series based operation

print("Original grades")
print(grades_named)

# Mathematical operations

print("\n+5 bonus points for everyone:")
print((grades_named+5).clip(upper=100))

print("\nDouble all grades:")
print((grades_named*2).clip(upper=200))

#Statistical operations
print("="*50)
print("STATISTICS")
print("="*50)
print(f"Mean (average): {grades_named.mean():.2f}")
print(f"Median: {grades_named.median():.2f}")
print(f"Standard deviation: {grades_named.std():.2f}")
print(f"Minimum: {grades_named.min()}")
print(f"Maximum: {grades_named.max()}")
print(f"Sum: {grades_named.sum()}")

Original grades
Math        85
Physics     90
Chemitry    78
Biology     82
CS          99
dtype: int64

+5 bonus points for everyone:
Math         90
Physics      95
Chemitry     83
Biology      87
CS          100
dtype: int64

Double all grades:
Math        170
Physics     180
Chemitry    156
Biology     164
CS          198
dtype: int64
==================================================
STATISTICS
==================================================
Mean (average): 86.80
Median: 85.00
Standard deviation: 8.11
Minimum: 78
Maximum: 99
Sum: 434

In [37]:
#Creating a DataFrame:


# From dict of lists
students_data = {
    'Name': ['Tuvya', 'Raj', 'Rahul', 'Priya', 'Arjun'],
    'Age': [18, 18, 19, 18, 19],
    'Math': [85, 92, 78, 90, 88],
    'Physics': [80, 88, 82, 85, 90],
    'Chemistry': [88, 90, 75, 92, 85]
}

df = pd.DataFrame(students_data)
print("Dataframe created")
display(df)

print("\nType: ",type(df))
print("Shape (rows,coloums):",df.shape)

Dataframe created

    Name  Age  Math  Physics  Chemistry
0  Tuvya   18    85       80         88
1    Raj   18    92       88         90
2  Rahul   19    78       82         75
3  Priya   18    90       85         92
4  Arjun   19    88       90         85

Type:  <class 'pandas.core.frame.DataFrame'>
Shape (rows,coloums): (5, 5)

In [36]:
# from list of dict
student_lists = [
    {
        'Name':'Tuvya',
        'Age':18,
        'CGPA' : 8.11
    },
    {
        'Name' : 'Raj',
        'Age': 18,
        'CGPA':8
    },
    {
        'Name':'Rahul',
        'Age':17,
        'CGPA':5
        
    }
]

df2 = pd.DataFrame(student_lists)
print("Dataframe from list of dict:")
display(df2)

Dataframe from list of dict:

    Name  Age  CGPA
0  Tuvya   18  8.11
1    Raj   18  8.00
2  Rahul   17  5.00

In [41]:
# From numpy array

data = np.array([
    [85, 80, 88],
    [92, 88, 90],
    [78, 82, 75]
])

df3 = pd.DataFrame(
    data,
    columns=['Math','Physics','English'],
    index=['Tuvya','Raj','Rohan']
)

print("Dataframe from NUmpy arrays:")
display(df3)

Dataframe from NUmpy arrays:

       Math  Physics  English
Tuvya    85       80       88
Raj      92       88       90
Rohan    78       82       75

In [49]:
print("Full DataFrame:")
display(df)
print("\n" + "=" * 60)

# head() - first N rows (default 5)
print("\nFirst 3 rows:")
display(df.head(3))

# tail() - last N rows
print("\nLast 2 rows:")
display(df.tail(2))

# info() - overview of DataFrame
print("\nDataFrame info:")
display(df.info())

# describe() - statistical summary
print("\nStatistical summary:")
display(df.describe())

Full DataFrame:

    Name  Age  Math  Physics  Chemistry
0  Tuvya   18    85       80         88
1    Raj   18    92       88         90
2  Rahul   19    78       82         75
3  Priya   18    90       85         92
4  Arjun   19    88       90         85

============================================================

First 3 rows:

    Name  Age  Math  Physics  Chemistry
0  Tuvya   18    85       80         88
1    Raj   18    92       88         90
2  Rahul   19    78       82         75

Last 2 rows:

    Name  Age  Math  Physics  Chemistry
3  Priya   18    90       85         92
4  Arjun   19    88       90         85

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   Math       5 non-null      int64
 3   Physics    5 non-null      int64
 4   Chemistry  5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

None

Statistical summary:

             Age       Math    Physics  Chemistry
count   5.000000   5.000000   5.000000   5.000000
mean   18.400000  86.600000  85.000000  86.000000
std     0.547723   5.458938   4.123106   6.670832
min    18.000000  78.000000  80.000000  75.000000
25%    18.000000  85.000000  82.000000  85.000000
50%    18.000000  88.000000  85.000000  88.000000
75%    19.000000  90.000000  88.000000  90.000000
max    19.000000  92.000000  90.000000  92.000000

In [53]:
# Accessing Coloums

# Method1 - Using bracket notation
print("All names")
print(df['Name'])
print("\nType:",type(df['Name']))

#MEthod2 - using dot notation(only if column nams has no space)
print("\nAll ages:")
print(df.Age)

print("\nName and Math scores:")
print(df[['Name','Math']])

All names
0    Tuvya
1      Raj
2    Rahul
3    Priya
4    Arjun
Name: Name, dtype: object

Type: <class 'pandas.core.series.Series'>

All ages:
0    18
1    18
2    19
3    18
4    19
Name: Age, dtype: int64

Name and Math scores:
    Name  Math
0  Tuvya    85
1    Raj    92
2  Rahul    78
3  Priya    90
4  Arjun    88

In [75]:
# Accessing Rows
print("First row (iloc[0]): ")
print(df.iloc[0])
print("\n",df2.iloc[0])
print("\n",df3.iloc[1])
print(f"\n{df['Name']}\n\n{df.loc[:,'Math']}")

First row (iloc[0]):
Name         Tuvya
Age             18
Math            85
Physics         80
Chemistry       88
Name: 0, dtype: object

 Name    Tuvya
Age        18
CGPA     8.11
Name: 0, dtype: object

 Math       92
Physics    88
English    90
Name: Raj, dtype: int64

0    Tuvya
1      Raj
2    Rahul
3    Priya
4    Arjun
Name: Name, dtype: object

0    85
1    92
2    78
3    90
4    88
Name: Math, dtype: int64